### PR TITLE
Added Offline Support

### PR DESCRIPTION
**Pull request by kavienanj**

### CODE REVIEW

**Comment by kavienanj** [comment]
Merge conflict was encountered too. I resolved it.

**Comment by sainiteshb** [comment]
Was it working fine? Any errors?

**Comment by kavienanj** [comment]
No errors. Well tested.

**Comment by kavienanj** [comment]
I added cached_network_image package. Please add it to the README.md file too.

**Comment by sainiteshb** [comment]
Okay I am adding it👍

**Pull request merged**
