### PR TITLE
Added More Features Like.Sharing App,Contact App,About Page and many more

### PR DESCRIPTION
**Pull request by vipuluthaiah**
455a653a-f981-41c1-82c0-e0066e9e3384
340b0cba-393b-40ae-b3ec-71a1dfd9f796
78fd4fa8-14e3-445e-af03-57da7f8f993d

### CODE REVIEW

**Comment by sainiteshb** [comment]
Did you change only the news view page?

**Comment by sainiteshb** [comment]
Can you please leave a recording of just using the app , just want to see how its working

**Comment by vipuluthaiah** [comment]
i only added new pages and there was some issue with loading ig it was api...so i just added new pages

**Comment by sainiteshb** [comment]
Alright great improvement👍

**Comment by vipuluthaiah** [comment]
future: news.getNews(),
this was giving some error..fix it my features willl not affect the app..what else u want me to add??

**Comment by sainiteshb** [comment]
At presesnt the app uses news Api , it has low API calls and if you have any alternative to change the current source of news info , with cache features , basically should be possible for more api calls . As far I know guardian api has more number of api calls, or your wish any other of your choice

**Pull request merged**
